### ISSUE TITLE
Documentação da regra de validação

### ISSUE THREAD

**Issue by dieisonbeck** [eihror/validaRenach#1]
Boa tarde, estou realizando validações de renach e gostaria de saber como conseguiu esta regra, tem algum documento que explica esse processo?

**Comment by eihror** [comment]
Fala cara, tudo bom? Eu infelizmente nesse momento não lembro onde foi que eu peguei essa regra de validação. mas o meu código está bem destrinchado e explicado. esse código está funcionando perfeitamente, pois na época eu precisei fazer um projeto que precisava disso como algo extremamente preciso e obrigatório... basta você transcrever para a linguagem que desejar.
